use_frameworks!

target 'SpecLeaks_Example' do
  pod 'SpecLeaks', :path => '../'


  target 'SpecLeaks_Tests' do
    inherit! :search_paths
    pod 'SpecLeaks', :path => '../'
    pod 'RxSwift'
    pod 'Quick'
    pod 'Nimble'
    pod 'RxCocoa'
  end
end
